volumes:
    postgres-data:

networks:
    timetracking-net:

services:
    pg-server:
      cap_add:
        - SYS_PTRACE
      image: postgres:15-bookworm
      # volumes:
      #   - postgres-data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=tk
        - POSTGRES_PASS=tkpassw0rd
        - POSTGRES_DB=tk
        - POSTGRES_HOST_AUTH_METHOD=trust
    redis-server:
      cap_add:
        - SYS_PTRACE
      image: redis:7-bookworm
      environment:
        REDIS_ARGS: "--requirepass foobared"
    tk-server:
      cap_add:
        - SYS_PTRACE
      ports:
        - 8080:8080
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      image: tk-server-release
      build:
        context: .
        dockerfile: docker/Dockerfile


